/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/phone.glb 
Author: Manuel W. (https://sketchfab.com/nebulariser)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smartphone-380280333c9f4fb8a21a53d18f6789e6
Title: Smartphone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/phone.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.909, 0.19, -0.494]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.Vidrio_Negro} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Vidrio_Negro} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Vidrio_Negro} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.Metal_Cromado} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Metal_Cromado} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Pantalla} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Pantalla} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Metal_Negro} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.Bandas_magneticas} />
          </group>
          <group position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_18.geometry} material={materials.Vidrio_Negro} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Metal_Cromado} />
          </group>
          <group position={[0.375, 0.875, -0.056]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.056}>
            <mesh geometry={nodes.Object_21.geometry} material={materials.Vidrio_Negro} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Metal_Cromado} />
          </group>
          <group position={[0, -0.986, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.01}>
            <mesh geometry={nodes.Object_32.geometry} material={materials.Metal_Ceramico} />
            <mesh geometry={nodes.Object_33.geometry} material={materials.Cobre} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Metal_Cromado} position={[0.505, 0.542, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.672, 1]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Metal_Cromado} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Camara} position={[0.375, 0.875, -0.047]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.039, 0.042, 0.039]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Luz_Led} position={[0.193, 0.912, -0.05]} rotation={[-Math.PI / 2, -1.392, Math.PI]} scale={0.028} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.Camara} position={[0.275, 0.875, -0.047]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.039, 0.042, 0.039]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Camara} position={[0, 0.849, 0.034]} rotation={[Math.PI / 2, 0, 0]} scale={[1.077, 1.032, 1.179]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Metal_Negro} position={[0, -0.952, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1.102, 1.03]} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.Metal_Negro} position={[0.219, -0.995, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.Metal_Negro} position={[-0.219, -0.993, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1.017, 1.102, 1.017]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/phone.glb')
